name: Validate pull request
on:
  pull_request:
    branches:
      - main
jobs:
  conventional-commits-pr:
    name: Validate Conventional Commits PR
    runs-on: ubuntu-latest
    steps:
      - uses: crazy-max/ghaction-dump-context@v1
      - uses: amannn/action-semantic-pull-request@v3.4.6
        with:
          types: |
            fix
            feat
            norelease
          validateSingleCommit: true
        env:
          GITHUB_TOKEN: ${{ github.token }}